### ISSUE TITLE
啥也不懂的小白来请教！

### ISSUE THREAD

**Issue by emmyes** [silie666/sina_luck_draw#1]
大佬 你这个咋用啊？

**Comment by silie666** [comment]
> 大佬 你这个咋用啊？

emm...，先把表导入到mysql，然后改下conf里面DB的mysql配置参数，SUB和UID换成自己的微博参数（网页F12看），go run main.go就可以了，之后不要上网页微博（手机可以上，用于观察），不然SUB这个值会被微博登录刷新

**Comment by YMXFffff** [comment]
还是没懂QAQ
