### ISSUE TITLE
执行go run main.go后无反应

### ISSUE THREAD

**Issue by nnlovestudy** [silie666/sina_luck_draw#2]
go已换源，如题

![image](https://user-images.githubusercontent.com/86106834/129602347-252de45f-f969-47af-9072-35761cea4648.png)

**Comment by silie666** [comment]
> 去已换源，如题
> 
> ![图像](https://user-images.githubusercontent.com/86106834/129602347-252de45f-f969-47af-9072-35761cea4648.png)

可以把main.go开头里的五分钟睡眠去掉，测试一下
