### ISSUE TITLE
不知道这样算成功了没。。

### ISSUE THREAD

**Issue by Dingtianqi329** [silie666/sina_luck_draw#7]
您好！小白想请教一个问题，运行时一直显示record not found是正常现象吗？一直没看见有转发有点晕
<img width="562" alt="截屏2022-11-02 22 03 45" src="https://user-images.githubusercontent.com/64207276/199510500-05a6505e-4e5e-4bbd-9b93-63d0ac7f3123.png">

**Comment by silie666** [comment]
> 您好！小白想请教一个问题，运行时一直显示record not found是正常现象吗？一直没看见有转发有点晕 <img alt="截屏2022-11-02 22 03 45" width="562" src="https://user-images.githubusercontent.com/64207276/199510500-05a6505e-4e5e-4bbd-9b93-63d0ac7f3123.png">

因为加了定时任务，过于频繁会被微博限制
